### ISSUE TITLE
Code Simplicity

### ISSUE THREAD

**Issue by Namatuzio** [Amnish04/til-page-builder#4]
The HTML file generation in `html_builder.py` can be further simplified by using a simple string while grabbing references to various elements of the text file and creating a string variable from that. Similar to something like this:

```python
text_content = """
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>""" + title + """</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <h1>""" + title + """</h1>
    <body>
        """ + file_contents + """
    </body>
</html>
"""
```

**Comment by Amnish04** [comment]
Hi @Namatuzio, I appreciate your advice. That was the original way I planned doing it.

However, since this approach requires lot of manual work by writing html strings, it didn't feel like the best approach to me.
Using yattag library with in-built functionality to generate tags just like `document.createElement` from javascript, is a much more scalable approach and eliminates the possibility of a lot of bugs that could occur due to typos in manual string formatting.
